// Generated by CoffeeScript 1.8.0

/*
Copyright (c) 2012-2013 [DeftJS Framework Contributors](http://deftjs.org)
Open source under the [MIT License](http://en.wikipedia.org/wiki/MIT_License).
 */

/**
* A collection of useful static methods for interacting with (and normalizing differences between) the Sencha Touch and Ext JS class systems.
* @private
 */
Ext.define('Deft.core.Class', {
  alternateClassName: ['Deft.Class'],
  statics: {

    /**
    		* Determines whether the passed Class reference is or extends the specified Class (by name).
    		*
    		* @return {Boolean} A Boolean indicating whether the specified Class reference is or extends the specified Class (by name)
     */
    extendsClass: function(targetClass, className) {
      var error;
      try {
        if (Ext.getClassName(targetClass) === className) {
          return true;
        }
        if (targetClass != null ? targetClass.superclass : void 0) {
          if (Ext.getClassName(targetClass.superclass) === className) {
            return true;
          } else {
            return Deft.Class.extendsClass(Ext.getClass(targetClass.superclass), className);
          }
        } else {
          return false;
        }
      } catch (_error) {
        error = _error;
        return false;
      }
    }
  }
});
